language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
sudo: required